version: '3.8'

services:
  spark-master:
    build: .
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
      - "4040:4040"
    volumes:
      - ./app:/app
      - ./archive:/archive
    working_dir: /app
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.master.Master

  spark-worker:
    build: .
    container_name: spark-worker
    depends_on:
      - spark-master
    volumes:
      - ./app:/app
    working_dir: /app
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077